if &cp | set nocp | endif
let s:cpo_save=&cpo

set t_Co=256 " 256 Colors
syntax on

set runtimepath=$HOME/.config/vim,$VIM,$VIMRUNTIME

""" BEGIN Plugins

if empty(glob('$HOME/.config/vim/autoload/plug.vim'))
    silent !curl -fLo $HOME/.config/vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Plugins

Plug 'machakann/vim-highlightedyank' " From vimcasts 72 ( I think)
Plug 'tpope/vim-vinegar'
Plug 'airblade/vim-gitgutter'
Plug 'chase/vim-ansible-yaml', { 'for': 'yaml' }
Plug 'christoomey/vim-tmux-navigator'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'easymotion/vim-easymotion'
Plug 'editorconfig/editorconfig-vim'
Plug 'gabesoft/vim-ags'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'lifepillar/vim-colortemplate', { 'for': 'vim' }
Plug 'lilydjwg/colorizer'
Plug 'lurst/austere.vim'
Plug 'majutsushi/tagbar'
Plug 'mxw/vim-jsx'
Plug 'mzlogin/vim-markdown-toc', {'for': 'markdown'}
Plug 'plasticboy/vim-markdown',  {'for': 'markdown'}
Plug 'rust-lang/rust.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'scrooloose/nerdtree'
Plug 'shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'tadaa/vimade'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-tbone'
Plug 'tpope/vim-vinegar'
Plug 'vim-scripts/L9'
Plug 'vim-scripts/taglist.vim'
Plug 'vimwiki/vimwiki'
Plug 'w0rp/ale'
Plug 'wincent/terminus'
Plug 'zchee/deoplete-jedi'

call plug#end()

filetype plugin indent on

let &cpo=s:cpo_save
unlet s:cpo_save

set background=dark
colorscheme austere

" Common Configuration
source $HOME/.config/vim/config/config.vim

" Plugins
source $HOME/.config/vim/config/plugins.vim

" Shortcuts
source $HOME/.config/vim/config/shortcuts.vim

" Macros
source $HOME/.config/vim/config/macros.vim

" Functions
source $HOME/.config/vim/config/functions.vim

" Plugin by Damian Conway
source $HOME/.config/vim/config/dragvisuals.vim
