" Common Configuration
source $HOME/.config/vim/config/config.vim

" Lua stuff
source $HOME/.config/vim/config/lua.lua

" Plugins
source $HOME/.config/vim/config/plugins.vim

" Shortcuts
source $HOME/.config/vim/config/shortcuts.vim

" Functions
source $HOME/.config/vim/config/functions.vim

" Colorscheme
source $HOME/.config/vim/config/colors.vim
