if &cp | set nocp | endif
let s:cpo_save=&cpo

set t_Co=256 " 256 Colors
syntax on

set runtimepath=$HOME/.config/vim,$VIM,$VIMRUNTIME

""" BEGIN Plugins

if empty(glob('$HOME/.config/vim/autoload/plug.vim'))
    silent !curl -fLo $HOME/.config/vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Plugins

Plug 'airblade/vim-gitgutter'
Plug 'alok/notational-fzf-vim'
Plug 'bogado/file-line'
Plug 'cespare/vim-toml'
Plug 'chase/vim-ansible-yaml', { 'for': 'yaml' }
Plug 'christoomey/vim-tmux-navigator'
Plug 'dense-analysis/ale'
Plug 'easymotion/vim-easymotion'
Plug 'editorconfig/editorconfig-vim'
Plug 'gabesoft/vim-ags'
Plug 'hotwatermorning/auto-git-diff'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/vim-peekaboo'
Plug 'lifepillar/vim-colortemplate', { 'for': 'vim' }
Plug 'lilydjwg/colorizer'
Plug 'liuchengxu/vim-which-key'
Plug 'machakann/vim-highlightedyank'
Plug 'majutsushi/tagbar'
Plug 'mxw/vim-jsx', { 'for': 'jsx' }
Plug 'plasticboy/vim-markdown',  {'for': 'markdown'}
Plug 'rust-lang/rust.vim', {'for': 'rust'}
Plug 'ryanoasis/vim-devicons'
Plug 'scrooloose/nerdtree'
Plug 'shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'
Plug 'vimwiki/vimwiki'
Plug 'zchee/deoplete-jedi'

" Coloschemes

Plug 'kristijanhusak/vim-hybrid-material'
Plug 'lurst/austere.vim'
Plug 'sainnhe/gruvbox-material'

call plug#end()

filetype plugin indent on

let &cpo=s:cpo_save
unlet s:cpo_save


" Colorscheme
source $HOME/.config/vim/config/colors.vim

" Common Configuration
source $HOME/.config/vim/config/config.vim

" Plugins
source $HOME/.config/vim/config/plugins.vim

" Shortcuts
source $HOME/.config/vim/config/shortcuts.vim

" Macros
source $HOME/.config/vim/config/macros.vim

" Functions
source $HOME/.config/vim/config/functions.vim

" Plugin by Damian Conway
source $HOME/.config/vim/config/dragvisuals.vim
