---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
   - name: Intel GPU + microcode
     pacman:
       name:
          - intel-ucode
          - intel-media-driver
          - vulkan-intel
          - intel-gpu-tools
       state: present
       update_cache: true
     when: "'GenuineIntel' in ansible_processor"

   - name: AMD GPU + microcode
     pacman:
       name:
          - amd-ucode
          - libva-mesa-driver
          - mesa-vdpau
          - vulkan-radeon
          - radeontop
       state: present
       update_cache: true
     when: "'AuthenticAMD' in ansible_processor"

   - name: Install things
     pacman:
       name:
          # My dev env
          - neovim
          - fzf
          - fd
          - entr
          - jq
          - openssh
          - fish
          - tmux
          - viewnior
          - ctags
          - imagemagick
          - bat
          - eza
          - ripgrep
          - uv
          - emacs
          - npm
          - just
          - tk
          - entr
          - pyright

          # OS
          - base
          - time
          - keychain
          - alacritty
          - pkgconf
          - tlp
          - tp_smapi
          - x86_energy_perf_policy
          - ttf-liberation
          - ttf-dejavu
          - ttf-cascadia-code-nerd
          - acpi
          - iwd
          - acpi_call-dkms
          - wireplumber
          - yt-dlp
          - htop
          - lsof
          - zip
          - 7zip
          - unzip
          - unrar
          - vlc
          - openbox
          - redshift
          - less

          # Extra
          - cmatrix
          - firefox
          - powertop
          - udisks2
          - ranger
          - stow
          - ufw
          - net-tools
          - libva-utils

          # For connecting with android
          - mtpfs
          - gvfs-mtp

          # For ranger
          - highlight
          - w3m

          # For samba share
          - gvfs-smb
       state: present
       update_cache: true
