---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
   - name: Install things
     pacman:
       name:
          # My dev env
          - neovim
          - fzf
          - fd
          - entr
          - jq
          - openssh
          - fish
          - tmux
          - viewnior
          - ctags
          - imagemagick
          - python-virtualenvwrapper
          - bat
          - eza
          - xsel
          - xclip
          - ripgrep
          - xfce4-clipman-plugin

          # OS
          - base
          - time
          - keychain
          - alacritty
          - pkgconf
          - intel-ucode
          - tlp
          - tp_smapi
          - x86_energy_perf_policy
          - ttf-liberation
          - ttf-dejavu
          - acpi
          - xorg-fonts-misc
          - xorg-xrandr
          - wireless_tools
          - yt-dlp
          - scrot
          - lxappearance
          - i3lock
          - xorg-server
          - xf86-video-intel
          - xorg-xinit
          - htop
          - lsof
          - zip
          - 7zip
          - unzip
          - unrar
          - feh
          - vlc
          - openbox
          - redshift
          - unclutter
          - arc-gtk-theme
          - arc-icon-theme

          # Extra
          - screenfetch
          - cmatrix
          - firefox
          - rofi
          - powertop
          - udisks2
          - pcmanfm
          - pavucontrol
          - ranger

          # For connecting with android
          - mtpfs
          - gvfs-mtp

          # For thumbnails in videos
          - ffmpegthumbnailer

          # For ranger
          - highlight
          - w3m

          # For samba share
          - gvfs-smb
       state: present
       update_cache: true
